on: 
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/archive_new_wells.yaml
      - R/archive_new_wells.R
#  schedule:
#    - cron: "0 6 * * *"      
jobs:
  job1:
    runs-on: ubuntu-latest
    container: 
      image: morglum/monrstudio
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_PAT }}
      BCGOV_GEOCODER_API: ${{ secrets.BCGOV_GEOCODER_API }}    
      BCGOV_DB: ${{ secrets.BCGOV_DB }}    
      BCGOV_HOST: ${{ secrets.BCGOV_HOST }}    
      BCGOV_PWD: ${{ secrets.BCGOV_PWD }}    
      BCGOV_USR: ${{ secrets.BCGOV_USR }}    
      
    steps:
      - uses: actions/checkout@v2
      - name : copy gwells_geocode python script
        run: | 
          mv data github_data 
          wget https://raw.githubusercontent.com/bcgov/GWELLS_LocationQA/main/gwells_locationqa.py
          mkdir /__w/gwells_geocode_and_archive_data/gwells_geocode_and_archive_data/data  
          touch /__w/gwells_geocode_and_archive_data/gwells_geocode_and_archive_data/data/touched  
#      - name: run download script
#        run:  |
#          ./python/download.sh
      - name: list files 
        run:  |
          ls * -lh
      - name: archive new wells
        run: |
          Rscript R/archive_new_wells.R            
      - name: list files  data
        run:  |
          ls data/*          
